---
version: v2.9.0

name: golangci-lint
destination: .

plugins:
  - module: fillmore-labs.com/cmplint
    import: fillmore-labs.com/cmplint/gclplugin
    path: .
  - module: fillmore-labs.com/scopeguard
    import: fillmore-labs.com/scopeguard/gclplugin
    version: v0.0.5
  - module: fillmore-labs.com/errortype
    import: fillmore-labs.com/errortype/gclplugin
    version: v0.0.9
